/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/noShadows.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/noShadows.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Default_Floor001.geometry} material={materials['Material.023']} position={[0, 3.198, 0]} scale={0.305} />
      <mesh geometry={nodes.gharniz.geometry} material={materials['Exterier Door']} scale={0.305} />
      <mesh geometry={nodes.Default_Floor.geometry} material={materials['Material.065']} scale={0.305} />
      <mesh geometry={nodes['Wood_-_Stained'].geometry} material={materials['windows metal']} position={[-1.458, 0.1, 6.379]} rotation={[0, 0.157, 0]} scale={0.305} />
      <mesh geometry={nodes['Clad_-_White'].geometry} material={nodes['Clad_-_White'].material} position={[-1.458, 0.1, 6.379]} rotation={[0, 0.157, 0]} scale={0.305} />
      <mesh geometry={nodes.Glass.geometry} material={materials['windows glass']} position={[0.797, 0, 5.108]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.MineralWool_ALUPROF_Brown.geometry} material={nodes.MineralWool_ALUPROF_Brown.material} position={[-3.365, 0, -7.256]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh geometry={nodes.Default_Wall.geometry} material={nodes.Default_Wall.material} scale={0.305} />
      <mesh geometry={nodes.Gypsum_Wall_Board.geometry} material={materials['Material.023']} scale={0.305} />
      <mesh geometry={nodes['B&B_MAXALTO_3_013'].geometry} material={materials['B&B_MAXALTO_3_tarelka0_dark.001']} position={[-1.352, 1.693, -4.372]} rotation={[Math.PI / 2, 0, 0.436]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_014'].geometry} material={materials['B&B_MAXALTO_3_tarelka1.001']} position={[-1.29, 2.027, -4.338]} rotation={[-3.054, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_017'].geometry} material={materials['B&B_MAXALTO_3_korpus.001']} position={[-1.082, 1.857, -4.279]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_020'].geometry} material={materials['B&B_MAXALTO_3_korpus.001']} position={[-1.281, 1.857, -4.331]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_094'].geometry} material={materials['B&B_MAXALTO_3_tarelka2.001']} position={[-1.09, 1.999, -4.285]} rotation={[-3.054, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_107'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.191, 1.675, -4.336]} rotation={[Math.PI / 2, 0, -Math.PI / 9]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_109'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.557, 1.678, -4.328]} rotation={[Math.PI / 2, 0, 0.148]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_121'].geometry} material={materials['B&B_MAXALTO_3_tarelka0_dark.001']} position={[-1.709, 1.547, -4.274]} rotation={[Math.PI, -0.463, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_123'].geometry} material={materials['Material.003']} position={[-1.443, 1.727, -4.354]} rotation={[Math.PI / 2, 0, 0.148]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_124'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.737, 1.674, -4.354]} rotation={[Math.PI / 2, 0, -0.637]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_134'].geometry} material={materials['B&B_MAXALTO_3_tarelka0_dark.001']} position={[-1.21, 1.548, -4.263]} rotation={[0, -0.436, 0]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_136'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-0.65, 1.643, -4.361]} rotation={[0, 0, -0.436]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_221'].geometry} material={materials['Material.064']} position={[-0.518, 1.614, -4.271]} rotation={[0, 0, 0.175]} scale={0.001} />
      <mesh geometry={nodes['B&B_MAXALTO_3_223'].geometry} material={materials['B&B_MAXALTO_3_Material #20037392.001']} position={[-1.048, 1.766, -4.384]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.049']} position={[0.99, 1.688, -3.723]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.341, 1, 1.153]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.051']} position={[0.995, 1.721, -2.821]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.055']} position={[0.99, 1.721, -2.821]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.053']} position={[0.99, 1.721, -1.904]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.054']} position={[0.995, 1.721, -1.904]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.056']} position={[0.995, 1.721, -0.952]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.057']} position={[0.99, 1.721, -0.952]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-0.83, 1.192, -4.347]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.351, 1, 1]} />
      <mesh geometry={nodes.Object02.geometry} material={materials.wire_214229166} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <group position={[2.75, 1.871, 1.251]} rotation={[-Math.PI, -0.939, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh029.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Mesh029_1.geometry} material={materials['AM109_051_BH.003']} />
        <mesh geometry={nodes.Mesh029_2.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[1.919, 1.028, 1.226]} rotation={[-Math.PI, 0, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh030.geometry} material={materials['AM109_051_hrom.003']} />
        <mesh geometry={nodes.Mesh030_1.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[1.497, 1.028, -0.163]} scale={0.01}>
        <mesh geometry={nodes.Mesh031.geometry} material={materials.AM109_050_hrom} />
        <mesh geometry={nodes.Mesh031_1.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[2.374, 1.291, -0.184]} rotation={[0, -1.083, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh032.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Mesh032_1.geometry} material={materials.AM109_050_BH} />
        <mesh geometry={nodes.Mesh032_2.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[3.612, 1.028, -0.174]} rotation={[-Math.PI, 0, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh036.geometry} material={materials['AM109_050_hrom.002']} />
        <mesh geometry={nodes.Mesh036_1.geometry} material={materials['AM109_051_hrom.004']} />
      </group>
      <group position={[3.66, 1.871, 0.107]} rotation={[-Math.PI, 0.405, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh037.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Mesh037_1.geometry} material={materials['AM109_050_BH.003']} />
        <mesh geometry={nodes.Mesh037_2.geometry} material={materials['AM109_051_hrom.005']} />
      </group>
      <group position={[3.637, 1.028, 0.982]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh038.geometry} material={materials['AM109_050_hrom.003']} />
        <mesh geometry={nodes.Mesh038_1.geometry} material={materials['AM109_051_hrom.005']} />
      </group>
      <group position={[-4.027, 1.291, -4.346]} rotation={[0, 0.487, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh039.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Mesh039_1.geometry} material={materials['AM109_050_BH.004']} />
        <mesh geometry={nodes.Mesh039_2.geometry} material={materials['AM109_051_hrom.006']} />
      </group>
      <group position={[-4.006, 1.028, -3.469]} rotation={[0, 1.571, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh040.geometry} material={materials['AM109_050_hrom.004']} />
        <mesh geometry={nodes.Mesh040_1.geometry} material={materials['AM109_051_hrom.006']} />
      </group>
      <group position={[-2.818, 1.028, -4.453]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh041.geometry} material={materials.AM109_055_hrom} />
        <mesh geometry={nodes.Mesh041_1.geometry} material={materials['Exterier Door']} />
      </group>
      <group position={[-3.693, 1.786, -4.429]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Mesh042.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Mesh042_1.geometry} material={materials['Exterier Door']} />
        <mesh geometry={nodes.Mesh042_2.geometry} material={materials.AM109_055_glassMilk} />
      </group>
      <group position={[-2.603, 0, 0.86]} scale={0.01}>
        <mesh geometry={nodes.Mesh028.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Mesh028_1.geometry} material={materials['Ficus_lyrata_material_2.001']} />
        <mesh geometry={nodes.Mesh028_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Mesh028_3.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Mesh028_4.geometry} material={materials['Material.006']} />
      </group>
      <mesh geometry={nodes.Lennox_Carpet_02001.geometry} material={materials['Lennox_Carpet_02.004']} position={[-0.406, 0, -2.071]} rotation={[0, -1.571, 0]} scale={0.001} />
      <group position={[-1.076, 0.386, -1.963]} rotation={[-Math.PI, 1.18, Math.PI / 2]} scale={0.001}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['book_white_11.002']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['stranici.001']} />
      </group>
      <group position={[-0.856, 0.382, -2.272]} rotation={[0, 0.257, -Math.PI / 2]} scale={0.001}>
        <mesh geometry={nodes.Mesh006.geometry} material={materials['book_white_11.003']} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials['stranici.002']} />
      </group>
      <group position={[-1.382, 0, 1.886]} rotation={[0, 0, Math.PI]} scale={-0.01}>
        <mesh geometry={nodes.Mesh115.geometry} material={materials['chairMinottiFilNoir_white_material_2.005']} />
        <mesh geometry={nodes.Mesh115_1.geometry} material={materials['chairMinottiFilNoir_white_material_2.005']} />
        <mesh geometry={nodes.Mesh115_2.geometry} material={materials['chairMinottiFilNoir_white_material_3.005']} />
        <mesh geometry={nodes.Mesh115_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh115_4.geometry} material={materials['chairMinottiFilNoir_white_material_5.005']} />
      </group>
      <group position={[-2.148, 0, 2.587]} rotation={[Math.PI, Math.PI / 2, 0]} scale={-0.01}>
        <mesh geometry={nodes.Mesh116.geometry} material={materials['chairMinottiFilNoir_white_material_2.005']} />
        <mesh geometry={nodes.Mesh116_1.geometry} material={materials['chairMinottiFilNoir_white_material_2.006']} />
        <mesh geometry={nodes.Mesh116_2.geometry} material={materials['chairMinottiFilNoir_white_material_3.006']} />
        <mesh geometry={nodes.Mesh116_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh116_4.geometry} material={materials['chairMinottiFilNoir_white_material_5.006']} />
      </group>
      <group position={[-0.451, 0, 2.607]} rotation={[0, Math.PI / 2, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh117.geometry} material={materials['chairMinottiFilNoir_white_material_2.005']} />
        <mesh geometry={nodes.Mesh117_1.geometry} material={materials['chairMinottiFilNoir_white_material_2.007']} />
        <mesh geometry={nodes.Mesh117_2.geometry} material={materials['chairMinottiFilNoir_white_material_3.007']} />
        <mesh geometry={nodes.Mesh117_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh117_4.geometry} material={materials['chairMinottiFilNoir_white_material_5.007']} />
      </group>
      <group position={[-1.375, 0, 3.517]} scale={0.01}>
        <mesh geometry={nodes.Mesh118.geometry} material={materials['chairMinottiFilNoir_white_material_2.005']} />
        <mesh geometry={nodes.Mesh118_1.geometry} material={materials['chairMinottiFilNoir_white_material_2.008']} />
        <mesh geometry={nodes.Mesh118_2.geometry} material={materials['chairMinottiFilNoir_white_material_3.008']} />
        <mesh geometry={nodes.Mesh118_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Mesh118_4.geometry} material={materials['chairMinottiFilNoir_white_material_5.008']} />
      </group>
      <group position={[-1.377, 3.05, 2.604]} scale={0.01}>
        <mesh geometry={nodes.Mesh114.geometry} material={materials['MoooiHeracleum_material_1_top.002']} />
        <mesh geometry={nodes.Mesh114_1.geometry} material={materials['MoooiHeracleum_material_2.002']} />
        <mesh geometry={nodes.Mesh114_2.geometry} material={materials['MoooiHeracleum_material_3.002']} />
        <mesh geometry={nodes.Mesh114_3.geometry} material={materials['MoooiHeracleum_material_4.002']} />
        <mesh geometry={nodes.Mesh114_4.geometry} material={materials['MoooiHeracleum_material_5.002']} />
        <mesh geometry={nodes.Mesh114_5.geometry} material={materials['MoooiHeracleum_material_6.002']} />
      </group>
      <group position={[-1.375, 0, 2.603]} scale={0.01}>
        <mesh geometry={nodes.Mesh093.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Mesh093_1.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Mesh093_2.geometry} material={materials['Table_Minotti_Morgan_material_3.002']} />
        <mesh geometry={nodes.Mesh093_3.geometry} material={materials['Material.029']} />
      </group>
      <mesh geometry={nodes.cook_018_00001.geometry} material={materials['01 - Default']} position={[-4.216, 0.901, 6.381]} rotation={[Math.PI, -0.152, Math.PI]} scale={0.025} />
      <mesh geometry={nodes.cook_018_01001.geometry} material={materials['01 - Default']} position={[-3.928, 0.906, 6.499]} rotation={[Math.PI, -0.152, Math.PI]} scale={0.025} />
      <mesh geometry={nodes.cook_018_02001.geometry} material={materials['03 - Default']} position={[-4.384, 0.901, 6.169]} rotation={[Math.PI, -0.152, Math.PI]} scale={0.025} />
      <mesh geometry={nodes.cook_018_03001.geometry} material={materials['02 - Default.001']} position={[-4.383, 0.923, 6.184]} rotation={[Math.PI, -0.152, Math.PI]} scale={[0.018, 0.025, 0.018]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.023']} position={[-0.332, 3.009, 5.005]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.011']} position={[-0.04, 1.721, 2.799]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.176, -2.035, -1.002]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.012']} position={[-0.045, 1.721, 2.799]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.135, -2.007, -0.976]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.015']} position={[-0.045, 1.721, 2.023]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.135, -2.007, -0.976]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.018']} position={[-0.04, 1.721, 2.023]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.176, -2.035, -1.002]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.047']} position={[0.99, 1.721, -3.723]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.050']} position={[0.995, 1.721, -3.723]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <group position={[-0.256, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh769.geometry} material={materials['book_white_7.002']} />
        <mesh geometry={nodes.Mesh769_1.geometry} material={materials['stranici.069']} />
      </group>
      <group position={[-0.229, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh770.geometry} material={materials['book_Gray_4.002']} />
        <mesh geometry={nodes.Mesh770_1.geometry} material={materials['stranici.070']} />
      </group>
      <group position={[-0.328, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh771.geometry} material={materials['book__13_1.001']} />
        <mesh geometry={nodes.Mesh771_1.geometry} material={materials['stranici.071']} />
      </group>
      <group position={[-0.307, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh772.geometry} material={materials['book_white_14.001']} />
        <mesh geometry={nodes.Mesh772_1.geometry} material={materials['stranici.072']} />
      </group>
      <group position={[-0.355, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh773.geometry} material={materials['book_black_10.002']} />
        <mesh geometry={nodes.Mesh773_1.geometry} material={materials['stranici.073']} />
      </group>
      <group position={[-0.283, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh774.geometry} material={materials['book_white_3.002']} />
        <mesh geometry={nodes.Mesh774_1.geometry} material={materials['stranici.074']} />
      </group>
      <group position={[-0.385, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh775.geometry} material={materials['book_white_1.002']} />
        <mesh geometry={nodes.Mesh775_1.geometry} material={materials['stranici.075']} />
      </group>
      <group position={[-0.411, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh776.geometry} material={materials['book__12_1.001']} />
        <mesh geometry={nodes.Mesh776_1.geometry} material={materials['stranici.076']} />
      </group>
      <group position={[-0.436, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh777.geometry} material={materials['book_white_4.002']} />
        <mesh geometry={nodes.Mesh777_1.geometry} material={materials['stranici.077']} />
      </group>
      <group position={[-0.457, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh778.geometry} material={materials['book_Gray_4.002']} />
        <mesh geometry={nodes.Mesh778_1.geometry} material={materials['stranici.070']} />
      </group>
      <group position={[-0.484, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh779.geometry} material={materials['book__14_1.001']} />
        <mesh geometry={nodes.Mesh779_1.geometry} material={materials['stranici.078']} />
      </group>
      <group position={[-0.514, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh780.geometry} material={materials['book_black_4.002']} />
        <mesh geometry={nodes.Mesh780_1.geometry} material={materials['stranici.079']} />
      </group>
      <group position={[-0.54, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh781.geometry} material={materials['book_white_8.002']} />
        <mesh geometry={nodes.Mesh781_1.geometry} material={materials['stranici.080']} />
      </group>
      <group position={[-0.565, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh782.geometry} material={materials['book_white_9.001']} />
        <mesh geometry={nodes.Mesh782_1.geometry} material={materials['stranici.081']} />
      </group>
      <group position={[-0.586, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh783.geometry} material={materials['book_black_1.001']} />
        <mesh geometry={nodes.Mesh783_1.geometry} material={materials['stranici.062']} />
      </group>
      <group position={[-0.613, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh784.geometry} material={materials['book_white_11.001']} />
        <mesh geometry={nodes.Mesh784_1.geometry} material={materials['stranici.082']} />
      </group>
      <group position={[-1.143, 1.252, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh750.geometry} material={materials['book_1_52.001']} />
        <mesh geometry={nodes.Mesh750_1.geometry} material={materials['stranici.061']} />
      </group>
      <group position={[-1.149, 1.297, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh751.geometry} material={materials['book_black_1.001']} />
        <mesh geometry={nodes.Mesh751_1.geometry} material={materials['stranici.062']} />
      </group>
      <group position={[-1.151, 1.336, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh752.geometry} material={materials['book_1_53.001']} />
        <mesh geometry={nodes.Mesh752_1.geometry} material={materials['stranici.063']} />
      </group>
      <group position={[-1.182, 1.377, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh753.geometry} material={materials['book_1_54.001']} />
        <mesh geometry={nodes.Mesh753_1.geometry} material={materials['stranici.064']} />
      </group>
      <group position={[-1.167, 1.417, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh754.geometry} material={materials['book_1_55.001']} />
        <mesh geometry={nodes.Mesh754_1.geometry} material={materials['stranici.065']} />
      </group>
      <group position={[-1.162, 1.478, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh755.geometry} material={materials['book_1_56.001']} />
        <mesh geometry={nodes.Mesh755_1.geometry} material={materials['stranici.066']} />
      </group>
      <group position={[-1.162, 1.451, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh756.geometry} material={materials['book_1_56.001']} />
        <mesh geometry={nodes.Mesh756_1.geometry} material={materials['stranici.066']} />
      </group>
      <group position={[-1.037, 1.375, -4.314]} rotation={[-Math.PI / 2, -0.262, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh757.geometry} material={materials['book_1_58.001']} />
        <mesh geometry={nodes.Mesh757_1.geometry} material={materials['stranici.067']} />
      </group>
      <group position={[-0.985, 1.371, -4.314]} rotation={[-Math.PI / 2, -Math.PI / 9, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh758.geometry} material={materials['book_1_59.001']} />
        <mesh geometry={nodes.Mesh758_1.geometry} material={materials['stranici.068']} />
      </group>
      <mesh geometry={nodes.fridge_007_00001.geometry} material={materials['fallback Material.007']} position={[-3.476, 0, 4.336]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_01001.geometry} material={materials['fallback Material.001']} position={[-3.476, 0, 4.336]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_02001.geometry} material={materials['fallback Material.001']} position={[-3.29, 1.466, 4.359]} scale={[0.025, 0.033, 0.025]} />
      <mesh geometry={nodes.fridge_007_03001.geometry} material={materials['fallback Material.002']} position={[-3.29, 1.669, 4.359]} scale={[0.025, 0.043, 0.025]} />
      <mesh geometry={nodes.fridge_007_04001.geometry} material={materials['fallback Material.002']} position={[-3.291, 0.322, 4.358]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.024, 0.031, 0.024]} />
      <mesh geometry={nodes.fridge_007_05001.geometry} material={materials['fallback Material.003']} position={[-3.736, 0.698, 4.081]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_06001.geometry} material={materials['fallback Material.003']} position={[-3.736, 0.444, 4.081]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_08001.geometry} material={materials['fallback Material.007']} position={[-3.696, 0.9, 4.658]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_09001.geometry} material={materials['fallback Material.001']} position={[-3.287, 0.895, 4.568]} scale={[0.038, 0.025, 0.025]} />
      <mesh geometry={nodes.fridge_007_10001.geometry} material={materials['fallback Material.001']} position={[-3.286, 0.897, 4.635]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_11001.geometry} material={materials['fallback Material.001']} position={[-3.286, 0.503, 4.592]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_12001.geometry} material={materials['fallback Material.002']} position={[-3.286, 0.503, 4.592]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_13001.geometry} material={materials['fallback Material.002']} position={[-3.286, 0.931, 4.592]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_14001.geometry} material={materials['fallback Material.001']} position={[-3.286, 0.931, 4.592]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_15001.geometry} material={materials['fallback Material.002']} position={[-3.286, 1.297, 4.592]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_16001.geometry} material={materials['fallback Material.001']} position={[-3.286, 1.297, 4.592]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_18001.geometry} material={materials['fallback Material.026']} position={[-3.2, 0.94, 4.586]} rotation={[-1.575, 0.009, -2.869]} scale={0.02} />
      <mesh geometry={nodes.fridge_007_19001.geometry} material={materials['fallback Material.027']} position={[-3.264, 0.513, 4.59]} rotation={[-Math.PI / 2, 0, 0.459]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_20001.geometry} material={materials['fallback Material.027']} position={[-3.172, 0.513, 4.589]} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_21001.geometry} material={materials['fallback Material.028']} position={[-3.415, 0.634, 4.589]} scale={0.02} />
      <mesh geometry={nodes.fridge_007_22001.geometry} material={materials['fallback Material.029']} position={[-3.203, 1.325, 4.609]} rotation={[-Math.PI / 2, 0, 0]} scale={0.019} />
      <mesh geometry={nodes.fridge_007_23001.geometry} material={materials['fallback Material.030']} position={[-3.184, 1.32, 4.595]} rotation={[-Math.PI / 2, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.fridge_007_24001.geometry} material={materials['fallback Material.031']} position={[-3.413, 0.941, 4.595]} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_25001.geometry} material={materials['fallback Material.032']} position={[-3.415, 0.634, 4.589]} scale={0.02} />
      <mesh geometry={nodes.fridge_007_26001.geometry} material={materials['fallback Material.033']} position={[-3.415, 0.634, 4.589]} scale={0.02} />
      <mesh geometry={nodes.fridge_007_27001.geometry} material={materials['fallback Material.034']} position={[-3.413, 0.941, 4.595]} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_28001.geometry} material={materials['fallback Material.035']} position={[-3.413, 0.941, 4.595]} rotation={[-Math.PI / 2, 0, 0]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_30001.geometry} material={materials['fallback Material.007']} position={[-3.744, 0.9, 4.658]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_31001.geometry} material={materials['fallback Material.001']} position={[-3.74, 0.895, 4.568]} scale={[0.026, 0.025, 0.025]} />
      <mesh geometry={nodes.fridge_007_32001.geometry} material={materials['fallback Material.001']} position={[-3.745, 1.453, 4.628]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.016, 0.016, 0.025]} />
      <mesh geometry={nodes.fridge_007_33001.geometry} material={materials['fallback Material.002']} position={[-3.745, 1.453, 4.628]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.016, 0.016, 0.025]} />
      <mesh geometry={nodes.fridge_007_34001.geometry} material={materials['fallback Material.001']} position={[-3.745, 0.537, 4.628]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.016, 0.016, 0.025]} />
      <mesh geometry={nodes.fridge_007_35001.geometry} material={materials['fallback Material.002']} position={[-3.745, 0.537, 4.628]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.016, 0.016, 0.025]} />
      <mesh geometry={nodes.fridge_007_36001.geometry} material={materials['fallback Material.036']} position={[-3.83, 1.132, 4.714]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_37001.geometry} material={materials['fallback Material.037']} position={[-3.833, 0.336, 4.356]} rotation={[-1.66, 1.246, 1.658]} scale={0.037} />
      <mesh geometry={nodes.fridge_007_38001.geometry} material={materials['fallback Material.037']} position={[-3.783, 0.331, 4.356]} rotation={[-1.639, 1.139, 1.633]} scale={0.037} />
      <mesh geometry={nodes.fridge_007_39001.geometry} material={materials['fallback Material.038']} position={[-3.279, 0.331, 4.323]} rotation={[-Math.PI / 2, 0, -1.833]} scale={0.003} />
      <mesh geometry={nodes.fridge_007_40001.geometry} material={materials['fallback Material.038']} position={[-3.332, 0.331, 4.323]} rotation={[-Math.PI / 2, 0, -2.269]} scale={0.003} />
      <mesh geometry={nodes.fridge_007_41001.geometry} material={materials['fallback Material.038']} position={[-3.351, 0.331, 4.241]} rotation={[-Math.PI / 2, 0, -2.705]} scale={0.003} />
      <mesh geometry={nodes.fridge_007_42001.geometry} material={materials['fallback Material.038']} position={[-3.328, 0.364, 4.323]} rotation={[-Math.PI / 2, 0, 2.094]} scale={0.003} />
      <mesh geometry={nodes.fridge_007_43001.geometry} material={materials['fallback Material.038']} position={[-3.367, 0.364, 4.352]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={0.003} />
      <mesh geometry={nodes.fridge_007_45001.geometry} material={materials['fallback Material.039']} position={[-3.34, 0.156, 4.349]} rotation={[-Math.PI / 2, 0, -0.96]} scale={0.011} />
      <mesh geometry={nodes.fridge_007_46001.geometry} material={materials['fallback Material.039']} position={[-3.311, 0.156, 4.423]} rotation={[-Math.PI / 2, -0.698, -2.356]} scale={0.011} />
      <mesh geometry={nodes.fridge_007_47001.geometry} material={materials['fallback Material.039']} position={[-3.26, 0.156, 4.365]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <mesh geometry={nodes.fridge_007_48001.geometry} material={materials['fallback Material.039']} position={[-3.305, 0.205, 4.376]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.fridge_007_49001.geometry} material={materials['fallback Material.040']} position={[-3.201, 0.717, 4.227]} rotation={[0.996, 0.269, 1.686]} scale={0.008} />
      <mesh geometry={nodes.fridge_007_50001.geometry} material={materials['fallback Material.040']} position={[-3.153, 0.717, 4.25]} rotation={[1.384, -0.092, 2.749]} scale={0.008} />
      <mesh geometry={nodes.fridge_007_51001.geometry} material={materials['fallback Material.040']} position={[-3.197, 0.717, 4.283]} rotation={[1.539, 0.454, 2.158]} scale={0.008} />
      <mesh geometry={nodes.fridge_007_52001.geometry} material={materials['fallback Material.040']} position={[-3.148, 0.717, 4.302]} rotation={[2.255, 0.592, -2.452]} scale={0.008} />
      <mesh geometry={nodes.fridge_007_53001.geometry} material={materials['fallback Material.040']} position={[-3.124, 0.717, 4.205]} rotation={[0.169, -0.832, -2.757]} scale={0.008} />
      <mesh geometry={nodes.fridge_007_54001.geometry} material={materials['fallback Material.033']} position={[-3.363, 0.692, 4.178]} rotation={[-Math.PI / 2, 0, 2.354]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_55001.geometry} material={materials['fallback Material.041']} position={[-3.363, 0.692, 4.178]} rotation={[-Math.PI / 2, 0, 2.354]} scale={0.015} />
      <mesh geometry={nodes.fridge_007_56001.geometry} material={materials['fallback Material.042']} position={[-3.81, 1.296, 4.286]} rotation={[-Math.PI / 2, 0, -0.62]} scale={0.018} />
      <mesh geometry={nodes.fridge_007_57001.geometry} material={materials['fallback Material.043']} position={[-3.308, 1.07, 4.326]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_58001.geometry} material={materials['fallback Material.031']} position={[-3.307, 1.063, 4.327]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.fridge_007_59001.geometry} material={materials['fallback Material.042']} position={[-3.671, 1.296, 4.286]} rotation={[-Math.PI / 2, 0, -0.009]} scale={0.018} />
      <mesh geometry={nodes.fridge_007_60001.geometry} material={materials['fallback Material.037']} position={[-3.724, 0.321, 4.356]} rotation={[-1.624, 1.005, 1.616]} scale={0.037} />
      <mesh geometry={nodes.Cylinder031001.geometry} material={materials['fallback Material.046']} position={[-5.409, 0.898, 5.599]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Box003001.geometry} material={materials['fallback Material.046']} position={[-5.592, 0.9, 5.44]} rotation={[-1.559, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Tube009001.geometry} material={materials['fallback Material.044']} position={[-5.592, 0.855, 5.637]} scale={0.001} />
      <mesh geometry={nodes.Cylinder027001.geometry} material={materials['fallback Material.044']} position={[-5.592, 0.666, 5.745]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Tube005001.geometry} material={materials['fallback Material.044']} position={[-5.592, 0.596, 5.745]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Line006001.geometry} material={materials['fallback Material.044']} position={[-5.629, 0.674, 5.745]} scale={0.001} />
      <mesh geometry={nodes.Torus004001.geometry} material={materials['fallback Material.046']} position={[-5.696, 1.15, 5.677]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes.Cylinder021001.geometry} material={materials['fallback Material.046']} position={[-5.774, 0.903, 5.599]} rotation={[-Math.PI / 2, 0, 2.356]} scale={0.001} />
      <mesh geometry={nodes.Cylinder020001.geometry} material={materials['fallback Material.044']} position={[-5.774, 0.898, 5.599]} rotation={[-Math.PI / 2, 0, 2.356]} scale={0.001} />
      <mesh geometry={nodes.Sphere004001.geometry} material={materials['fallback Material.044']} position={[-5.783, 1.015, 5.59]} rotation={[0, Math.PI / 4, 0]} scale={0.001} />
      <mesh geometry={nodes.Cylinder019001.geometry} material={materials['fallback Material.046']} position={[-5.823, 1.011, 5.556]} rotation={[Math.PI, -Math.PI / 4, 0]} scale={0.001} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['fallback Material.046']} position={[-5.809, 0.898, 5.805]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.objBox01.geometry} material={materials.wire_214229166} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objBox04.geometry} material={materials['20 - Default']} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <group position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025}>
        <mesh geometry={nodes.Mesh052.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Mesh052_1.geometry} material={materials['20___Default']} />
      </group>
      <mesh geometry={nodes.Object01.geometry} material={materials.wire_214229166} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objLine01.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objLine02.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objLine03.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objPlane02.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objPlane03.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objPlane04.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objRectangle02.geometry} material={materials.wire_086086086} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objRectangle03.geometry} material={materials.wire_154154229} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objVCD_1.geometry} material={materials['21 - Default']} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh geometry={nodes.objvcd_2.geometry} material={materials['21 - Default']} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <group position={[-2.626, 0.007, -3.224]} rotation={[0, -1.571, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh132.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Mesh132_1.geometry} material={materials['Lennox_Pillow_B_02.004']} />
        <mesh geometry={nodes.Mesh132_2.geometry} material={materials['Lennox_Pillow_C_02.004']} />
      </group>
      <mesh geometry={nodes.Lennox_Plaid_02001.geometry} material={materials['Erica_Plaid_02.004']} position={[-0.315, 2.263, -2.824]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <group position={[0.167, 0.337, -2.657]} rotation={[0, -1.571, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh130.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Mesh130_1.geometry} material={materials['Legs_Gloss_02.004']} />
        <mesh geometry={nodes.Mesh130_2.geometry} material={materials['Legs_Matte_02.004']} />
      </group>
      <mesh geometry={nodes.DCSU_Decor_007001.geometry} material={materials['DCSU_Decor_04.004']} position={[-0.842, 0.398, -2.263]} rotation={[-3.111, -1.36, -3.096]} scale={0.001} />
      <mesh geometry={nodes.DCSU_Decor_008001.geometry} material={materials['DCSU_Decor_02.004']} position={[-0.896, 0.367, -1.68]} rotation={[0, -Math.PI / 2, 0]} scale={0.001} />
      <group position={[-0.959, 0.351, -2.06]} rotation={[0, -1.571, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh061.geometry} material={materials['Verve_CTable_Top_02.004']} />
        <mesh geometry={nodes.Mesh061_1.geometry} material={materials['Legs_Gloss_02.004']} />
        <mesh geometry={nodes.Mesh061_2.geometry} material={materials['Legs_Matte_02.004']} />
      </group>
      <mesh geometry={nodes.Cap004.geometry} material={materials['cap_material_2.007']} position={[-0.785, 0.735, 2.594]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cap2004.geometry} material={materials['cap_material_1.007']} position={[-0.785, 0.741, 2.594]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Fork004.geometry} material={materials['Fork_material.005']} position={[-0.785, 0.729, 2.748]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Fork2004.geometry} material={materials['Fork_material.005']} position={[-0.763, 0.729, 2.775]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Knife004.geometry} material={materials['Fork_material.005']} position={[-0.798, 0.728, 2.442]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Spoon004.geometry} material={materials['Fork_material.005']} position={[-0.795, 0.733, 2.408]} rotation={[-Math.PI, 1.535, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cap005.geometry} material={materials['cap_material_2.007']} position={[-1.973, 0.735, 2.571]} rotation={[0, -1.385, 0]} scale={0.01} />
      <mesh geometry={nodes.Cap2005.geometry} material={materials['cap_material_1.007']} position={[-1.972, 0.741, 2.571]} rotation={[0, -1.385, 0]} scale={0.01} />
      <mesh geometry={nodes.Fork005.geometry} material={materials['Fork_material.006']} position={[-1.995, 0.729, 2.419]} rotation={[0, -1.385, 0]} scale={0.01} />
      <mesh geometry={nodes.Fork2005.geometry} material={materials['Fork_material.006']} position={[-2.021, 0.729, 2.395]} rotation={[0, -1.385, 0]} scale={0.01} />
      <mesh geometry={nodes.Knife005.geometry} material={materials['Fork_material.006']} position={[-1.938, 0.728, 2.72]} rotation={[0, -1.385, 0]} scale={0.01} />
      <mesh geometry={nodes.Spoon005.geometry} material={materials['Fork_material.006']} position={[-1.935, 0.733, 2.753]} rotation={[0, -1.385, 0]} scale={0.01} />
      <mesh geometry={nodes.Cap006.geometry} material={materials['cap_material_2.007']} position={[-1.37, 0.735, 1.997]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cap2006.geometry} material={materials['cap_material_1.007']} position={[-1.371, 0.741, 1.997]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Fork006.geometry} material={materials['Fork_material.007']} position={[-1.217, 0.729, 2.008]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Fork2006.geometry} material={materials['Fork_material.007']} position={[-1.188, 0.729, 1.987]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Knife006.geometry} material={materials['Fork_material.007']} position={[-1.523, 0.728, 1.999]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Spoon006.geometry} material={materials['Fork_material.007']} position={[-1.556, 0.733, 1.994]} rotation={[-Math.PI, 0.033, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cap007.geometry} material={materials['cap_material_2.007']} position={[-1.394, 0.735, 3.203]} scale={0.01} />
      <mesh geometry={nodes.Cap2007.geometry} material={materials['cap_material_1.007']} position={[-1.394, 0.741, 3.203]} scale={0.01} />
      <mesh geometry={nodes.Fork007.geometry} material={materials['Fork_material.008']} position={[-1.548, 0.729, 3.198]} scale={0.01} />
      <mesh geometry={nodes.Fork2007.geometry} material={materials['Fork_material.008']} position={[-1.576, 0.729, 3.219]} scale={0.01} />
      <mesh geometry={nodes.Knife007.geometry} material={materials['Fork_material.008']} position={[-1.241, 0.728, 3.196]} scale={0.01} />
      <mesh geometry={nodes.Spoon007.geometry} material={materials['Fork_material.008']} position={[-1.208, 0.733, 3.2]} scale={0.01} />
      <mesh geometry={nodes.Object_1.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Custom} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.Custom} />
    </group>
  )
}

useGLTF.preload('/noShadows.glb')
